config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show] do
    get :search, on: :collection
  end
  resources :shopping_carts
  resources :addresses do
    member do
      put :set_default_address
    end
  end
  resources :orders
  resources :payments, only: [:index] do
    collection do
      get :generate_pay
      get :pay_return
      get :pay_notify
      get :success
      get :failed
    end
  end
  resources :cellphone_tokens, only: [:create]

  namespace :dashboard do
    scope 'profile' do
      controller :profile do
        get :password
        put :update_password
      end
    end

    resources :orders, only: [:index]
    resources :addresses, only: [:index]
  end

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord

  validates :user_uuid, presence: true
  validates :product_id, presence: true
  validates :amount, presence: true

  belongs_to :product

  scope :by_user_uuid, -> (user_uuid) { where(user_uuid: user_uuid) }

  def self.create_or_update! options = {}
    cond = {
      user_uuid: options[:user_uuid],
      product_id: options[:product_id]
    }

    record = where(cond).first
    if record
      record.update_attributes!(options.merge(amount: record.amount + options[:amount]))
    else
      record = create!(options)
    end

    record
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  before_action :find_shopping_cart, only: [:update, :destroy]

  def index
    fetch_home_data
    @shopping_carts = ShoppingCart.by_user_uuid(session[:user_uuid])
      .order("id desc").includes([:product => [:main_product_image]])
  end

  def create
    amount = params[:amount].to_i
    amount = amount <= 0 ? 1 : amount

    @product = Product.find(params[:product_id])
    @shopping_cart = ShoppingCart.create_or_update!({
      user_uuid: session[:user_uuid],
      product_id: params[:product_id],
      amount: amount
    })

    render layout: false
  end

  def update
    if @shopping_cart
      amount = params[:amount].to_i
      amount = amount <= 0 ? 1 : amount

      @shopping_cart.update_attribute :amount, amount
    end

    redirect_to shopping_carts_path
  end

  def destroy
    @shopping_cart.destroy if @shopping_cart

    redirect_to shopping_carts_path
  end

  private
  def find_shopping_cart
    @shopping_cart = ShoppingCart.by_user_uuid(session[:user_uuid])
      .where(id: params[:id]).first
  end

end

app/views/shopping_carts/create.html.erb
<div class="modal fade" tabindex="-1" id="shopping_cart_modal">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="text text-success"><i class='fa fa-check-circle-o'></i> 加入购物车成功</h4>

        <div class="media">
          <div class="media-left">
            <a href="javascript:;">
              <%= image_tag @product.main_product_image.image.url(:small), class: 'media-object', alt: @product.title %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= @product.title %></h4>
            数量: <%= @shopping_cart.amount %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">继续购物</button>
        <%= link_to "查看购物车", shopping_carts_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shopping_carts/index.html.erb
<h1>购物车 (<%= @shopping_carts.count %>)</h1>
<div class="row">
  <div class="container">
    <div class="alert alert-info">
      <% unless @shopping_carts.blank? %>
        <% @shopping_carts.each do |shopping_cart| %>
          <div class="media shopping-cart-row">
            <div class="media-left">
              <a href="<%= product_path(shopping_cart.product) %>">
                <%= image_tag shopping_cart.product.main_product_image.image.url(:small), class: 'media-object', alt: shopping_cart.product.title %>
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= link_to shopping_cart.product.title, product_path(shopping_cart.product) %></h4>
              数量: <%= shopping_cart.amount %> 价格: ¥<%= shopping_cart.amount * shopping_cart.product.price %>
            </div>
            <div class="media-right">
              <%= form_tag shopping_cart_path(shopping_cart), method: :put do %>
                <p><input type="text" name="amount" value="<%= shopping_cart.amount %>" /></p>
                <p>
                  <%= submit_tag "更新", class: "btn btn-default btn-xs" %>
                  <%= link_to "删除", shopping_cart_path(shopping_cart), method: :delete, 'data-confirm': "不考虑一下了?", class: "btn btn-default btn-xs" %>
                </p>
              <% end -%>
            </div>
          </div>
        <% end -%>
      <% else %>
        <h3>购物车为空</h3>
      <% end -%>
    </div>

    <% unless @shopping_carts.blank? %>
      <div class="pull-right">
        <strong>总价: ¥<%= @shopping_carts.sum { |cart| cart.amount * cart.product.price } %></strong>
        &nbsp;
        <%= link_to "去结算", new_order_path, class: "btn btn-danger btn-lg" %>
      </div>
      <div class="clearfix"></div>
    <% end %>
  </div>
</div>