config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show] do
    get :search, on: :collection
  end
  resources :shopping_carts
  resources :addresses do
    member do
      put :set_default_address
    end
  end
  resources :orders
  resources :payments, only: [:index] do
    collection do
      get :generate_pay
      get :pay_return
      get :pay_notify
      get :success
      get :failed
    end
  end
  resources :cellphone_tokens, only: [:create]

  namespace :dashboard do
    scope 'profile' do
      controller :profile do
        get :password
        put :update_password
      end
    end

    resources :orders, only: [:index]
    resources :addresses, only: [:index]
  end

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/views/shared/_categories.html.erb
<ul class="list-group">
  <% @categories.each do |group| %>
    <li class="list-group-item"><%= group.first.title %></li>
    <% group.last.each do |sub_category| %>
      <li class="list-group-item"><a href="<%= category_path(sub_category) %>"><%= sub_category.title %></a></li>
    <% end -%>
  <% end -%>
</ul>

app/views/shared/_products.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(product.main_product_image.image.url(:middle), alt: product.title), product_path(product) %>
        <div class="caption">
          <h4><%= link_to product.title, product_path(product), class: 'title' %></h4>
          <p><strong>¥<%= product.price %></strong> <span class="msrp">¥<%= product.msrp %></span></p>
          <p><%= show_add_to_cart product, html_class: "btn-xs" %></p>
        </div>
      </div>
    </div>
  <% end -%>
</div>

<%= will_paginate @products %>