config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show] do
    get :search, on: :collection
  end
  resources :shopping_carts
  resources :addresses do
    member do
      put :set_default_address
    end
  end
  resources :orders
  resources :payments, only: [:index] do
    collection do
      get :generate_pay
      get :pay_return
      get :pay_notify
      get :success
      get :failed
    end
  end
  resources :cellphone_tokens, only: [:create]

  namespace :dashboard do
    scope 'profile' do
      controller :profile do
        get :password
        put :update_password
      end
    end

    resources :orders, only: [:index]
    resources :addresses, only: [:index]
  end

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, presence: { message: "名称不能为空" }
  validates :title, uniqueness: { message: "名称不能重复" }

  has_ancestry orphan_strategy: :destroy

  has_many :products, dependent: :destroy

  before_validation :correct_ancestry

  def self.grouped_data
    self.roots.order("weight desc").inject([]) do |result, parent|
      row = []
      row << parent
      row << parent.children.order("weight desc")
      result << row
    end
  end

  private
  def correct_ancestry
    self.ancestry = nil if self.ancestry.blank?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  before_action :find_root_categories, only: [:new, :create, :edit, :update]
  before_action :find_category, only: [:edit, :update, :destroy]
  
  def index
    if params[:id].blank?
      @categories = Category.roots
    else
      @category = Category.find(params[:id])
      @categories = @category.children
    end

    @categories = @categories.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order(id: "desc")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit!)

    if @category.save
      flash[:notice] = "保存成功"
      redirect_to admin_categories_path
    else
      render action: :new
    end
  end

  def edit
    render action: :new
  end

  def update
    @category.attributes = params.require(:category).permit!

    if @category.save
      flash[:notice] = "修改成功"
      redirect_to admin_categories_path
    else
      render action: :new
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "删除成功"
      redirect_to admin_categories_path
    else
      flash[:notice] = "删除失败"
      redirect_to :back
    end
  end

  private
  def find_root_categories
    @root_categories = Category.roots.order(id: "desc")
  end

  def find_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    fetch_home_data
    
    @category = Category.find(params[:id])
    @products = @category.products.onshelf.page(params[:page] || 1).per_page(params[:per_page] || 12)
      .order("id desc").includes(:main_product_image)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div>
  <div class="pull-right">
    <%= link_to "新建分类", new_admin_category_path, class: "btn btn-primary" %>
  </div>

  <h1>
    <% if @category %>
      分类:<%= @category.title %>(<%= @categories.total_entries %>)
    <% else %>
      分类(<%= @categories.total_entries %>)
    <% end -%>
  </h1>
</div>

<div>
  <table class="table table-striped">
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>Weight</th>
      <th></th>
    </tr>

    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.title %></td>
        <td><%= category.weight %></td>
        <td align="right">
          <%= link_to "编辑", edit_admin_category_path(category) %> 
          <%= link_to "删除", admin_category_path(category), method: :delete, 'data-confirm': "确认删除吗?" %>
          <% if category.root? %>
            <%= link_to "查看子分类", admin_categories_path(id: category) %>
          <% end -%>
        </td>
      </tr>
    <% end -%>
  </table>

  <%= will_paginate @categories %>
</div>

app/views/admin/categories/new.html.erb
<div>
  <h1><%= @category.new_record? ? "新建分类" : "修改分类 ##{params[:id]}" %></h1>
</div>

<div class="form-body">
  <%= form_for @category, 
    url: (@category.new_record? ? admin_categories_path : admin_category_path(@category)), 
    method: (@category.new_record? ? 'post' : 'put'), 
    html: { class: 'form-horizontal' } do |f| %>
    
    <% unless @category.errors.blank? %>
      <div class="alert alert-danger">
        <ul class="list-unstyled">
          <% @category.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
    <% end -%>

    <div class="form-group">
      <label for="ancestry" class="col-sm-2 control-label">所属分类:</label>
      <div class="col-sm-5">
        <select name="category[ancestry]">
          <option></option>
          <% @root_categories.each do |category| %>
            <% next if category == @category %>
            <option value="<%= category.id %>" <%= @category.ancestry == category.id.to_s ? 'selected' : '' %>><%= category.title %></option>
          <% end -%>
        </select>
        为空为一级分类
      </div>
    </div>
    <div class="form-group">
      <label for="title" class="col-sm-2 control-label">名称:*</label>
      <div class="col-sm-5">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="weight" class="col-sm-2 control-label">权重:</label>
      <div class="col-sm-5">
        <%= f.text_field :weight, class: "form-control" %> 数值越大越靠前
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit (@category.new_record? ? "新建分类" : "编辑分类"), class: "btn btn-default" %>
      </div>
    </div>
  <% end -%>
</div>